services:
  # FastAPI Backend Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./data:/app/data
    environment:
      - CHROMA_HOST=chroma
      - CHROMA_PORT=8000
    depends_on:
      - chroma
    networks:
      - rag-network

  # ChromaDB Vector Database Service
  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    volumes:
      - chroma-data:/data
    ports:
      - "8100:8000"  # Mapea el puerto 8000 interno al 8100 externo
    networks:
      - rag-network

  # PostgreSQL Service with pgvector
  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=khoj
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - rag-network
      
  # Khoj Service
  khoj:
    image: khoj-ai/khoj:latest
    ports:
      - "4000:4000"
    volumes:
      - khoj-data:/data
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/khoj
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=khoj
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - KHOJ_ADMIN_EMAIL=admin@example.com
      - KHOJ_ADMIN_PASSWORD=supersecurepassword
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - rag-network

  # Frontend Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - rag-network

networks:
  rag-network:
    driver: bridge

volumes:
  chroma-data:
  khoj-data:
  postgres-data: